export const CALL_LIST_REQUEST = 'CALL_LIST_REQUEST'
export const CALL_LIST_SUCCESS = 'CALL_LIST_SUCCESS'
export const CALL_LIST_FAIL = 'CALL_LIST_FAIL'

export const CALL_DETAIL_REQUEST = 'CALL_DETAIL_REQUEST'
export const CALL_DETAIL_SUCCESS = 'CALL_DETAIL_SUCCESS'
export const CALL_DETAIL_FAIL = 'CALL_DETAIL_FAIL'