export const CALL_LIST_REQUEST = 'CALL_LIST_REQUEST'
export const CALL_LIST_SUCCESS = 'CALL_LIST_SUCCESS'
export const CALL_LIST_FAIL = 'CALL_LIST_FAIL'

export const CALL_DETAIL_REQUEST = 'CALL_DETAIL_REQUEST'
export const CALL_DETAIL_SUCCESS = 'CALL_DETAIL_SUCCESS'
export const CALL_DETAIL_FAIL = 'CALL_DETAIL_FAIL'

export const CALL_DELETE_REQUEST = 'CALL_DELETE_REQUEST'
export const CALL_DELETE_SUCCESS = 'CALL_DELETE_SUCCESS'
export const CALL_DELETE_FAIL = 'CALL_DELETE_FAIL'

export const CALL_CREATE_REQUEST = 'CALL_CREATE_REQUEST'
export const CALL_CREATE_SUCCESS = 'CALL_CREATE_SUCCESS'
export const CALL_CREATE_FAIL = 'CALL_CREATE_FAIL'
export const CALL_CREATE_RESET = 'CALL_CREATE_RESET'

export const CALL_UPDATE_REQUEST = 'CALL_UPDATE_REQUEST'
export const CALL_UPDATE_SUCCESS = 'CALL_UPDATE_SUCCESS'
export const CALL_UPDATE_FAIL = 'CALL_UPDATE_FAIL'
export const CALL_UPDATE_RESET = 'CALL_UPDATE_RESET'