export const SERVICES_LIST_REQUEST = 'SERVICES_LIST_REQUEST'
export const SERVICES_LIST_SUCCESS = 'SERVICES_LIST_SUCCESS'
export const SERVICES_LIST_FAIL = 'SERVICES_LIST_FAIL'

export const SERVICES_DETAIL_REQUEST = 'SERVICES_DETAIL_REQUEST'
export const SERVICES_DETAIL_SUCCESS = 'SERVICES_DETAIL_SUCCESS'
export const SERVICES_DETAIL_FAIL = 'SERVICES_DETAIL_FAIL'